language: rust
os:
  - linux
  - windows
  - osx
rust:
  - stable
cache: cargo
branches:
  only:
    - master
script:
  - cargo build --verbose
  - cargo doc --no-deps --verbose
  - cargo test --verbose
env:
  - RUST_BACKTRACE=1