language: rust
os:
  - linux
  - windows
  - osx
rust:
  - stable
cache: cargo
branches:
  only:
    - master
script:
  - cargo build
  - cargo build --no-default-features
  - cargo test
env:
  - RUST_BACKTRACE=1