[package]
name = "quickcfg"
version = "0.1.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
description = """
Do basic configuration of a system, declaratively and quickly.
"""
edition = "2018"

[dependencies]
serde = "1"
serde_derive = "1"
serde_yaml = "0.8"
failure = "0.1.3"
relative-path = {version = "0.4", features = ["serde"]}
clap = "2.32"
rayon = "1"
ignore = "0.4"
log = "0.4"
pretty_env_logger = "0.2"
handlebars = "1.1"
directories = "1"
